# Generated by Django 5.0.6 on 2025-12-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_task_fri_task_mon_task_sat_task_sun_task_thu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=60),
        ),
    ]
